/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: (typeof import('element-plus/es'))['ElAside'];
    ElBacktop: (typeof import('element-plus/es'))['ElBacktop'];
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElCard: (typeof import('element-plus/es'))['ElCard'];
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
    ElContainer: (typeof import('element-plus/es'))['ElContainer'];
    ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions'];
    ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem'];
    ElForm: (typeof import('element-plus/es'))['ElForm'];
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
    ElHeader: (typeof import('element-plus/es'))['ElHeader'];
    ElInput: (typeof import('element-plus/es'))['ElInput'];
    ElLink: (typeof import('element-plus/es'))['ElLink'];
    ElMain: (typeof import('element-plus/es'))['ElMain'];
    ElMenu: (typeof import('element-plus/es'))['ElMenu'];
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
    ElSpace: (typeof import('element-plus/es'))['ElSpace'];
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
    ElTag: (typeof import('element-plus/es'))['ElTag'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    YText: (typeof import('./../src/components/y-text/index.vue'))['default'];
  }
}
